(deffacts AGENT::maneuvers-to-validate
    (ASK overtaking-maneuver)
    (ASK right-turn-maneuver)
    (ASK left-turn-maneuver)
    (ASK change-lane-maneuver)
    (ASK give-priority-maneuver)
    (ASK stop-car-maneuver)
    (ASK reduce-speed-maneuver)
    (ASK accelerate-maneuver)
    (ASK pull-right-maneuver)
    (ASK pull-left-maneuver)
    (ASK keep-going-maneuver)
)
